### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by firebirdberlin** [firebirdberlin/rocketlaunch#4]
Galaxy S6 - Android 5.1

```
FATAL EXCEPTION: AsyncTask #4
Process: com.firebirdberlin.rocketlaunch, PID: 26701
 java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
    at com.firebirdberlin.rocketlaunch.RocketLaunch$CacheIconsTask.doInBackground(RocketLaunch.java:446)
    at com.firebirdberlin.rocketlaunch.RocketLaunch$CacheIconsTask.doInBackground(RocketLaunch.java:410)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
```

**Comment by firebirdberlin** [comment]
This issue is fixed by the means that it no longer crashes the app. The reason where icons using a LayerDrawble. This seems to be the case for the facebook app. These apps are shown in the app drawer, but the icon is left empty. Thus this issue needs improvement.
